import 'package:flutter/material.dart';
import 'package:insta_image_viewer/insta_image_viewer.dart';
import 'package:intl/intl.dart';

import '../Utils/app_them.dart';

class AdminTemplateListScreen extends StatefulWidget {
  const AdminTemplateListScreen({super.key});

  @override
  State<AdminTemplateListScreen> createState() => _AdminTemplateListScreenState();
}

class _AdminTemplateListScreenState extends State<AdminTemplateListScreen> {
  @override
  Widget build(BuildContext context) {
    return
      Scaffold(
        appBar: AppBar(backgroundColor: AppThem.appBgColor,
          title: const Text("Select Template",style: TextStyle(color: Colors.white),),),
        body: ListView(
          scrollDirection: Axis.horizontal,
          children: [
            Padding(
              padding: EdgeInsets.all(10.0),
              child: Center(
                child: Container(
                  height: MediaQuery.of(context).size.height * 0.6,
                  width: MediaQuery.of(context).size.width * 0.9,
                  padding: const EdgeInsets.only(bottom: 20),
                  // Adds space at the bottom of the container
                  decoration: BoxDecoration(
                    border: Border.all(width: 2, color: Colors.green),
                  ),
                  child: Column(
                    children: [
                      const Padding(
                        padding: EdgeInsets.only(top: 10),
                        child: Text(
                          "ABC Store",
                          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                        ),
                      ),
                      const SizedBox(height: 10),
                      const Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Padding(
                            padding: EdgeInsets.only(top: 12),
                            child: Text(
                              "Generated By",
                              style: TextStyle(
                                  fontSize: 12, fontWeight: FontWeight.bold),
                            ),
                          ),
                          SizedBox(width: 5),
                          CircleAvatar(radius: 10,backgroundImage: AssetImage("assets/images/udaan_biz_logo.png"),),
                          SizedBox(width: 5),
                          Text(
                            "UdaanBiz",
                            style: TextStyle(fontSize: 12),
                          ),
                        ],
                      ),
                      const SizedBox(height: 10),
                       Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const Padding(
                            padding: EdgeInsets.only(top: 10.0, left: 0.0),
                            child: Text(
                              "Bill Date",
                              style: TextStyle(
                                  fontSize: 12, fontWeight: FontWeight.bold),
                            ),
                          ),
                          const SizedBox(width: 5),
                          const Icon(
                            Icons.date_range,
                            color: Colors.green,
                            size: 18,
                          ),
                          SizedBox(width: 5),
                          Text(DateFormat('dd-MM-yyyy').format(DateTime.now(),),style: TextStyle(fontSize: 12),),
                        ],
                      ),
                      SizedBox(height: 10),
                      const Padding(
                        padding: EdgeInsets.symmetric(horizontal: 10),
                        child: Divider(
                          color: Colors.green,
                          thickness: 2,
                          indent: 0,
                          endIndent: 0,
                        ),
                      ),
                      const Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Padding(
                            padding: EdgeInsets.only(left: 8.0, top: 5.0),
                            child: Text('Product Item 1'),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 140.0, top: 5.0),
                            child: Text('Rate (₹)'),
                          ),
                        ],
                      ),
                      const SizedBox(height: 10),
                      Padding(
                        padding: const EdgeInsets.only(left: 10),
                        child: Row(
                          children: List.generate(
                            32,
                                (index) => Container(
                              margin: const EdgeInsets.symmetric(horizontal: 2),
                              height: 2,
                              width: 5,
                              color: Colors.green,
                            ),
                          ),
                        ),
                      ),
                      Expanded(
                        child: ListView.builder(
                          itemCount: 5,
                          itemBuilder: (context, index) => Row(
                            children: [
                              Padding(
                                padding: EdgeInsets.only(left: 5, top: 10),
                                child: Text("Product Item ${index + 1}"),
                              ),
                              const Padding(
                                padding: EdgeInsets.only(left: 160, top: 10),
                                child: Text("1500/"),
                              ),
                            ],
                          ),
                        ),
                      ),
                      const Padding(
                        padding: EdgeInsets.symmetric(horizontal: 10),
                        child: Divider(
                          color: Colors.green,
                          thickness: 1,
                          indent: 0,
                          endIndent: 0,
                        ),
                      ),
                      const Row(
                        children: [
                          Padding(
                            padding: EdgeInsets.only(left: 10, top: 5),
                            child: Text("Total Amount"),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 150, top: 5),
                            child: Text("75000/"),
                          ),
                        ],
                      ),
                      Row(
                        children: [
                          Padding(
                            padding: const EdgeInsets.only(left: 10, top: 5),
                            child: InstaImageViewer(
                              child: Container(
                                height: 40,
                                width: 40,
                                child: Image.asset(
                                  "assets/images/shakil_upi_scaner.jpg",
                                ),
                              ),
                            ),
                          ),
                          Padding(
                            padding: const EdgeInsets.only(left: 170, top: 5),
                            child: IconButton(
                                onPressed: () {},
                                icon: const Icon(
                                  Icons.send,
                                  color: Colors.green,
                                  size: 30,
                                )),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
            ),
            Padding(
              padding: EdgeInsets.all(10.0),
              child: Center(
                child: Container(
                  height: MediaQuery.of(context).size.height * 0.6,
                  width: MediaQuery.of(context).size.width * 0.9,
                  padding: const EdgeInsets.only(bottom: 20),
                  // Adds space at the bottom of the container
                  decoration: BoxDecoration(
                    border: Border.all(width: 2, color: Colors.green),
                  ),
                  child: Column(
                    children: [
                      const Padding(
                        padding: EdgeInsets.only(top: 10),
                        child: Text(
                          "ANAND GENERAL STORE \n Chhapra Maker ",
                          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                        ),
                      ),
                      const SizedBox(height: 10),
                      const Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Padding(
                            padding: EdgeInsets.only(top: 10),
                            child: Text(
                              "Generated By",
                              style: TextStyle(
                                  fontSize: 12, fontWeight: FontWeight.bold),
                            ),
                          ),
                          SizedBox(width: 5),
                          Icon(
                            Icons.local_grocery_store_outlined,
                            color: Colors.green,
                            size: 18,
                          ),
                          SizedBox(width: 5),
                          Text(
                            "UdaanBiz",
                            style: TextStyle(fontSize: 12),
                          ),
                        ],
                      ),
                      const SizedBox(height: 10),
                      const Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Padding(
                            padding: EdgeInsets.only(top: 10.0, left: 0.0),
                            child: Text(
                              "Bill Date",
                              style: TextStyle(
                                  fontSize: 12, fontWeight: FontWeight.bold),
                            ),
                          ),
                          SizedBox(width: 5),
                          Icon(
                            Icons.date_range,
                            color: Colors.green,
                            size: 18,
                          ),
                          SizedBox(width: 5),
                          Text(
                            "22/12/2024",
                            style: TextStyle(fontSize: 12),
                          ),
                        ],
                      ),
                      SizedBox(height: 10),
                      const Padding(
                        padding: EdgeInsets.symmetric(horizontal: 10),
                        child: Divider(
                          color: Colors.green,
                          thickness: 2,
                          indent: 0,
                          endIndent: 0,
                        ),
                      ),
                      const Row(
                        //Previous Due Date
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Padding(
                            padding: EdgeInsets.only(left: 8.0, top: 5.0),
                            child: Text('Previous Due Date'),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 120.0, top: 5.0),
                            child: Text('Rate (₹)'),
                          ),
                        ],
                      ),
                      const SizedBox(height: 10),
                      Padding(
                        padding: const EdgeInsets.only(left: 10),
                        child: Row(
                          children: List.generate(
                            32,
                                (index) => Container(
                              margin: const EdgeInsets.symmetric(horizontal: 2),
                              height: 2,
                              width: 5,
                              color: Colors.green,
                            ),
                          ),
                        ),
                      ),
                      Expanded(
                        child: ListView.builder(
                          itemCount: 5,
                          itemBuilder: (context, index) => Row(
                            children: [
                              Padding(
                                padding: EdgeInsets.only(left: 5, top: 10),
                                child: Text("13/12/2024 Due ${index + 1}"),
                              ),
                              Padding(
                                padding: EdgeInsets.only(left: 140, top: 10),
                                child: Text("1500/"),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Padding(
                        padding: EdgeInsets.symmetric(horizontal: 10),
                        child: Divider(
                          color: Colors.green,
                          thickness: 1,
                          indent: 0,
                          endIndent: 0,
                        ),
                      ),
                      Row(
                        children: [
                          Padding(
                            padding: EdgeInsets.only(left: 10, top: 5),
                            child: Text("Total Amount"),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 150, top: 5),
                            child: Text("75000/"),
                          ),
                        ],
                      ),
                      Row(
                        children: [
                          Padding(
                            padding: const EdgeInsets.only(left: 10, top: 5),
                            child: InstaImageViewer(
                              child: Container(
                                height: 40,
                                width: 40,
                                child: Image.asset(
                                  "assets/images/shakil_upi_scaner.jpg",
                                ),
                              ),
                            ),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 170, top: 5),
                            child: IconButton(
                                onPressed: () {},
                                icon: Icon(
                                  Icons.send,
                                  color: Colors.green,
                                  size: 30,
                                )),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
            ),
            Padding(
              padding:  const EdgeInsets.all(10.0),
              child: Center(
                child: Container(
                  height: 500,
                  width: 400,
                  padding: const EdgeInsets.only(bottom: 20),  // Adds space at the bottom of the container
                  decoration: BoxDecoration(
                    border: Border.all(width: 2, color: Colors.green),
                  ),
                  child: Column(
                    children: [
                      const Padding(
                        padding: EdgeInsets.only(top: 10),
                        child: Text(
                          "ABC Store",
                          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                        ),
                      ),
                      const SizedBox(height: 10),
                      const Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Padding(
                            padding: EdgeInsets.only(top: 10),
                            child: Text(
                              "Generated By",
                              style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                            ),
                          ),
                          SizedBox(width: 5),
                          Icon(
                            Icons.local_grocery_store_outlined,
                            color: Colors.green,
                            size: 18,
                          ),
                          SizedBox(width: 5),
                          Text(
                            "UdaanBiz",
                            style: TextStyle(fontSize: 12),
                          ),
                        ],
                      ),
                       const SizedBox(height: 10),
                       Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const Padding(
                            padding: EdgeInsets.only(top: 10.0, left: 0.0),
                            child: Text(
                              "Bill Date",
                              style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                            ),
                          ),
                          const SizedBox(width: 5),
                          const Icon(
                            Icons.date_range,
                            color: Colors.green,
                            size: 18,
                          ),
                          SizedBox(width: 5),
                          // DateFormat('dd-MM-yyyy').format(DateTime.now()
                          Text(DateFormat('dd-MM-yyyy').format(DateTime.now(),),style: TextStyle(fontSize: 12),
                          ),

                        ],
                      ),
                      const SizedBox(height: 10),
                      const Padding(
                        padding: EdgeInsets.symmetric(horizontal: 10),
                        child: Divider(
                          color: Colors.green,
                          thickness: 2,
                          indent: 0,
                          endIndent: 0,
                        ),
                      ),
                      const Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Padding(
                            padding: EdgeInsets.only(left: 8.0, top: 5.0),
                            child: Text('Product Item 1'),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 160.0, top: 5.0),
                            child: Text('Rate (₹)'),
                          ),
                        ],
                      ),
                      const SizedBox(height: 10),
                      Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 10),
                        child: Row(
                          children: List.generate(
                            35,
                                (index) => Container(
                              margin: const EdgeInsets.symmetric(horizontal: 2),
                              height: 2,
                              width: 5,
                              color: Colors.green,
                            ),
                          ),
                        ),
                      ),
                      Expanded(
                        child: ListView.builder(
                          itemCount: 5,
                          itemBuilder: (context, index) => Row(
                            children: [
                              Padding(
                                padding: EdgeInsets.only(left: 5, top: 10),
                                child: Text("Product Item ${index + 1}"),
                              ),
                              const Padding(
                                padding: EdgeInsets.only(left: 160, top: 10),
                                child: Text("1500/"),
                              ),
                            ],
                          ),
                        ),
                      ),
                      const Padding(
                        padding: EdgeInsets.symmetric(horizontal: 10),
                        child: Divider(
                          color: Colors.green,
                          thickness: 1,
                          indent: 0,
                          endIndent: 0,
                        ),
                      ),
                      const Row(
                        children: [
                          Padding(
                            padding: EdgeInsets.only(left: 10, top: 5),
                            child: Text("Total Amount"),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 150, top: 5),
                            child: Text("75000/"),
                          ),
                        ],
                      ),
                      Row(
                        children: [
                          Padding(
                            padding: const EdgeInsets.only(left: 10, top: 5),
                            child: InstaImageViewer(
                              child: Container(
                                height: 40,
                                width: 40,
                                child: Image.asset(
                                  "assets/images/shakil_upi_scaner.jpg",
                                ),
                              ),
                            ),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 170, top: 5),
                            child: IconButton(onPressed: () {

                            }, icon: Icon(Icons.send,color: Colors.green,size: 30,)),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
            ),
            Padding(
              padding:  EdgeInsets.all(10.0),
              child: Center(
                child: Container(
                  height: 500,
                  width: 400,
                  padding: const EdgeInsets.only(bottom: 20),
                  decoration: BoxDecoration(
                    border: Border.all(width: 2, color: Colors.green),
                  ),
                  child: Column(
                    children: [
                      const Padding(
                        padding: EdgeInsets.only(top: 10),
                        child: Text(
                          "ABC Store",
                          style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                        ),
                      ),
                      const SizedBox(height: 10),
                      const Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Padding(
                            padding: EdgeInsets.only(top: 10),
                            child: Text(
                              "Generated By",
                              style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                            ),
                          ),
                          SizedBox(width: 5),
                          Icon(
                            Icons.local_grocery_store_outlined,
                            color: Colors.green,
                            size: 18,
                          ),
                          SizedBox(width: 5),
                          Text(
                            "UdaanBiz",
                            style: TextStyle(fontSize: 12),
                          ),
                        ],
                      ),
                      const SizedBox(height: 10),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const Padding(
                            padding: EdgeInsets.only(top: 10.0, left: 0.0),
                            child: Text(
                              "Bill Date",
                              style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                            ),
                          ),
                          const SizedBox(width: 5),
                          const Icon(
                            Icons.date_range,
                            color: Colors.green,
                            size: 18,
                          ),
                          const SizedBox(width: 5),
                          Text(DateFormat('dd-MM-yyyy').format(DateTime.now(),),style: const TextStyle(fontSize: 12),),
                        ],
                      ),
                      const SizedBox(height: 10),
                      const Padding(
                        padding: EdgeInsets.symmetric(horizontal: 10),
                        child: Divider(
                          color: Colors.green,
                          thickness: 2,
                          indent: 0,
                          endIndent: 0,
                        ),
                      ),
                      const Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Padding(
                            padding: EdgeInsets.only(left: 8.0, top: 5.0),
                            child: Text('Product Item 1'),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 160.0, top: 5.0),
                            child: Text('Rate (₹)'),
                          ),
                        ],
                      ),
                      const SizedBox(height: 10),
                      Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 10),
                        child: Row(
                          children: List.generate(
                            35,
                                (index) => Container(
                              margin: const EdgeInsets.symmetric(horizontal: 2),
                              height: 2,
                              width: 5,
                              color: Colors.green,
                            ),
                          ),
                        ),
                      ),
                      Expanded(
                        child: ListView.builder(
                          itemCount: 5,
                          itemBuilder: (context, index) => Row(
                            children: [
                              Padding(
                                padding: EdgeInsets.only(left: 5, top: 10),
                                child: Text("Product Item ${index + 1}"),
                              ),
                              const Padding(
                                padding: EdgeInsets.only(left: 160, top: 10),
                                child: Text("1500/"),
                              ),
                            ],
                          ),
                        ),
                      ),
                      const Padding(
                        padding: EdgeInsets.symmetric(horizontal: 10),
                        child: Divider(
                          color: Colors.green,
                          thickness: 1,
                          indent: 0,
                          endIndent: 0,
                        ),
                      ),
                      const Row(
                        children: [
                          Padding(
                            padding: EdgeInsets.only(left: 10, top: 5),
                            child: Text("Total Amount"),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 150, top: 5),
                            child: Text("75000/"),
                          ),
                        ],
                      ),
                      Row(
                        children: [
                          Padding(
                            padding: const EdgeInsets.only(left: 10, top: 5),
                            child: InstaImageViewer(
                              child: Container(
                                height: 40,
                                width: 40,
                                child: Image.asset(
                                  "assets/images/shakil_upi_scaner.jpg",
                                ),
                              ),
                            ),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 170, top: 5),
                            child: IconButton(onPressed: () {

                            }, icon: Icon(Icons.send,color: Colors.green,size: 30,)),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
            )
          ],
        ),
      );
  }

  void datePiker() async{
    DateTime? datePicker = await showDatePicker(context: context,
        firstDate: DateTime(2020),
        initialDate: DateTime.now(),
        lastDate: DateTime.now());
    if(datePicker != null){
      print("date selected ${datePicker.day}");
    }
  }
}