import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:insta_image_viewer/insta_image_viewer.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';

import '../Utils/app_them.dart';
import '../ViewModels/transition_history_provider.dart';
import '../ViewModels/user_profile_provider.dart';
import '../ViewModels/user_provider.dart';

class AdminTemplateListScreen extends StatefulWidget {
  final int? id;
  const AdminTemplateListScreen({super.key, required this.id});

  @override
  State<AdminTemplateListScreen> createState() => _AdminTemplateListScreenState();
}

class _AdminTemplateListScreenState extends State<AdminTemplateListScreen> {
  late UserProvider userProvider;
  late UserProfileProvider userProfileProvider;
  late TransitionHistoryProvider creditProvider;

  @override
  void initState() {
    super.initState();
    userProvider = Provider.of<UserProvider>(context, listen: false);
    super.initState();
    userProvider.showData();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      Provider.of<UserProfileProvider>(context, listen: false)
          .showProfileData();

      creditProvider =
          Provider.of<TransitionHistoryProvider>(context, listen: false);
      creditProvider.usersId = widget.id!;
      creditProvider.showAmountTransition();});
  }

  @override
  Widget build(BuildContext context) {
    var   profileData = Provider.of<UserProfileProvider>(context, listen: false);
    return
      Scaffold(
        appBar: AppBar(backgroundColor: AppThem.appBgColor,
          title: const Text("Select Template",style: TextStyle(color: Colors.white),),),
        body:Consumer<UserProfileProvider>(builder: (context, value, child) {
          value.userProfile.toSet().toList();
          return ListView(
            scrollDirection: Axis.horizontal,
            children: [
              Padding(
                padding: const EdgeInsets.all(10.0),
                child: Center(
                  child: Container(
                    height: MediaQuery.of(context).size.height * 0.6,
                    width: MediaQuery.of(context).size.width * 0.9,
                    padding: const EdgeInsets.only(bottom: 20),
                    // Adds space at the bottom of the container
                    decoration: BoxDecoration(
                      border: Border.all(width: 2, color: Colors.green),
                    ),
                    child: Column(
                      children: [
                         Padding(
                          padding: EdgeInsets.only(top: 10),
                          child: Text(
                            "ABC Store",
                            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                          ),
                        ),
                        const SizedBox(height: 10),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 12),
                              child: Text(
                                "Generated By",
                                style: TextStyle(
                                    fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            CircleAvatar(radius: 10,backgroundImage: AssetImage("assets/images/udaan_biz_logo.png"),),
                            SizedBox(width: 5),
                            Text(
                              "UdaanBiz",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Padding(
                              padding: EdgeInsets.only(top: 10.0, left: 0.0),
                              child: Text(
                                "Bill Date",
                                style: TextStyle(
                                    fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            const SizedBox(width: 5),
                            const Icon(
                              Icons.date_range,
                              color: Colors.green,
                              size: 18,
                            ),
                            const SizedBox(width: 5),
                            Text(DateFormat('dd-MM-yyyy').format(DateTime.now(),),style: const TextStyle(fontSize: 12),),
                          ],
                        ),
                        const SizedBox(height: 10),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 2,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 8.0, top: 5.0),
                              child: Text('Product Item 1'),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 140.0, top: 5.0),
                              child: Text('Rate (₹)'),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Padding(
                          padding: const EdgeInsets.only(left: 10),
                          child: Row(
                            children: List.generate(
                              32,
                                  (index) => Container(
                                margin: const EdgeInsets.symmetric(horizontal: 2),
                                height: 2,
                                width: 5,
                                color: Colors.green,
                              ),
                            ),
                          ),
                        ),
                        Expanded(
                          child:Consumer<TransitionHistoryProvider>(builder: (context, value, child) {
                            value.transitionList.toSet().toList();
                            return ListView.builder(
                              itemCount:value.transitionList.length ,

                              itemBuilder: (context, index){
                                var item = value.transitionList[index];
                                bool isReceived = item.isReceived == 'isReceive';
                                return isReceived ?
                                Row(
                                  children: [
                                    Padding(
                                      padding: const EdgeInsets.only(left: 5, top: 10),
                                      child: Text("Product Item ${index + 1}"),
                                    ),
                                    Padding(
                                      padding: const EdgeInsets.only(left: 160, top: 10),
                                      child: Text(item.loanedMoney.toString()+"/"),
                                    ),
                                  ],
                                ): const CircularProgressIndicator();
                              },
                            );
                          },),
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 1,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 10, top: 5),
                              child: Text("Total Amount"),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 150, top: 5),
                              child: Text("75000/"),
                            ),
                          ],
                        ),
                        Row(
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(left: 10, top: 5),
                              child: InstaImageViewer(
                                child: SizedBox(
                                  height: 40,
                                  width: 40,
                                  child: Image.asset(
                                    "assets/images/shakil_upi_scaner.jpg",
                                  ),
                                ),
                              ),
                            ),
                            Padding(
                              padding: const EdgeInsets.only(left: 170, top: 5),
                              child: IconButton(
                                  onPressed: () {},
                                  icon: const Icon(
                                    Icons.send,
                                    color: Colors.green,
                                    size: 30,
                                  )),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(10.0),
                child: Center(
                  child: Container(
                    height: MediaQuery.of(context).size.height * 0.6,
                    width: MediaQuery.of(context).size.width * 0.9,
                    padding: const EdgeInsets.only(bottom: 20),
                    // Adds space at the bottom of the container
                    decoration: BoxDecoration(
                      border: Border.all(width: 2, color: Colors.green),
                    ),
                    child: Column(
                      children: [
                        const Padding(
                          padding: EdgeInsets.only(top: 10),
                          child: Text(
                            "ANAND GENERAL STORE \n Chhapra Maker ",
                            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                          ),
                        ),
                        const SizedBox(height: 10),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 10),
                              child: Text(
                                "Generated By",
                                style: TextStyle(
                                    fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            Icon(
                              Icons.local_grocery_store_outlined,
                              color: Colors.green,
                              size: 18,
                            ),
                            SizedBox(width: 5),
                            Text(
                              "UdaanBiz",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 10.0, left: 0.0),
                              child: Text(
                                "Bill Date",
                                style: TextStyle(
                                    fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            Icon(
                              Icons.date_range,
                              color: Colors.green,
                              size: 18,
                            ),
                            SizedBox(width: 5),
                            Text(
                              "22/12/2024",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 2,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          //Previous Due Date
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 8.0, top: 5.0),
                              child: Text('Previous Due Date'),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 120.0, top: 5.0),
                              child: Text('Rate (₹)'),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Padding(
                          padding: const EdgeInsets.only(left: 10),
                          child: Row(
                            children: List.generate(
                              32,
                                  (index) => Container(
                                margin: const EdgeInsets.symmetric(horizontal: 2),
                                height: 2,
                                width: 5,
                                color: Colors.green,
                              ),
                            ),
                          ),
                        ),
                        Expanded(
                          child:Consumer<TransitionHistoryProvider>(builder: (context, value, child) {
                            value.transitionList.toSet().toList();
                            return ListView.builder(
                              itemCount: 5,
                              itemBuilder: (context, index) => Row(
                                children: [
                                  Padding(
                                    padding: const EdgeInsets.only(left: 5, top: 10),
                                    child: Text("13/12/2024 Due ${index + 1}"),
                                  ),
                                  const Padding(
                                    padding: EdgeInsets.only(left: 140, top: 10),
                                    child: Text("1500/"),
                                  ),
                                ],
                              ),
                            );
                          },),
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 1,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 10, top: 5),
                              child: Text("Total Amount"),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 150, top: 5),
                              child: Text("75000/"),
                            ),
                          ],
                        ),
                        Row(
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(left: 10, top: 5),
                              child: InstaImageViewer(
                                child: SizedBox(
                                  height: 40,
                                  width: 40,
                                  child: Image.asset(
                                    "assets/images/shakil_upi_scaner.jpg",
                                  ),
                                ),
                              ),
                            ),
                            Padding(
                              padding: const EdgeInsets.only(left: 170, top: 5),
                              child: IconButton(
                                  onPressed: () {},
                                  icon: const Icon(
                                    Icons.send,
                                    color: Colors.green,
                                    size: 30,
                                  )),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Padding(
                padding:  const EdgeInsets.all(10.0),
                child: Center(
                  child: Container(
                    height: 500,
                    width: 400,
                    padding: const EdgeInsets.only(bottom: 20),  // Adds space at the bottom of the container
                    decoration: BoxDecoration(
                      border: Border.all(width: 2, color: Colors.green),
                    ),
                    child: Column(
                      children: [
                        const Padding(
                          padding: EdgeInsets.only(top: 10),
                          child: Text(
                            "ABC Store",
                            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                          ),
                        ),
                        const SizedBox(height: 10),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 10),
                              child: Text(
                                "Generated By",
                                style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            Icon(
                              Icons.local_grocery_store_outlined,
                              color: Colors.green,
                              size: 18,
                            ),
                            SizedBox(width: 5),
                            Text(
                              "UdaanBiz",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Padding(
                              padding: EdgeInsets.only(top: 10.0, left: 0.0),
                              child: Text(
                                "Bill Date",
                                style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            const SizedBox(width: 5),
                            const Icon(
                              Icons.date_range,
                              color: Colors.green,
                              size: 18,
                            ),
                            const SizedBox(width: 5),
                            // DateFormat('dd-MM-yyyy').format(DateTime.now()
                            Text(DateFormat('dd-MM-yyyy').format(DateTime.now(),),style: const TextStyle(fontSize: 12),
                            ),

                          ],
                        ),
                        const SizedBox(height: 10),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 2,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 8.0, top: 5.0),
                              child: Text('Product Item 1'),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 160.0, top: 5.0),
                              child: Text('Rate (₹)'),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 10),
                          child: Row(
                            children: List.generate(
                              35,
                                  (index) => Container(
                                margin: const EdgeInsets.symmetric(horizontal: 2),
                                height: 2,
                                width: 5,
                                color: Colors.green,
                              ),
                            ),
                          ),
                        ),
                        Expanded(
                          child:Consumer<TransitionHistoryProvider>(builder: (context, value, child) {
                            value.transitionList.toSet().toList();
                            return ListView.builder(
                              itemCount: 5,
                              itemBuilder: (context, index) => Row(
                                children: [
                                  Padding(
                                    padding: const EdgeInsets.only(left: 5, top: 10),
                                    child: Text("Product Item ${index + 1}"),
                                  ),
                                  const Padding(
                                    padding: EdgeInsets.only(left: 160, top: 10),
                                    child: Text("1500/"),
                                  ),
                                ],
                              ),
                            );
                          },),
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 1,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 10, top: 5),
                              child: Text("Total Amount"),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 150, top: 5),
                              child: Text("75000/"),
                            ),
                          ],
                        ),
                        Row(
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(left: 10, top: 5),
                              child: InstaImageViewer(
                                child: SizedBox(
                                  height: 40,
                                  width: 40,
                                  child: Image.asset(
                                    "assets/images/shakil_upi_scaner.jpg",
                                  ),
                                ),
                              ),
                            ),
                            Padding(
                              padding: const EdgeInsets.only(left: 170, top: 5),
                              child: IconButton(onPressed: () {

                              }, icon: const Icon(Icons.send,color: Colors.green,size: 30,)),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Padding(
                padding:  const EdgeInsets.all(10.0),
                child: Center(
                  child: Container(
                    height: 500,
                    width: 400,
                    padding: const EdgeInsets.only(bottom: 20),
                    decoration: BoxDecoration(
                      border: Border.all(width: 2, color: Colors.green),
                    ),
                    child: Column(
                      children: [
                        const Padding(
                          padding: EdgeInsets.only(top: 10),
                          child: Text(
                            "ABC Store",
                            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                          ),
                        ),
                        const SizedBox(height: 10),
                        const Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(top: 10),
                              child: Text(
                                "Generated By",
                                style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            SizedBox(width: 5),
                            Icon(
                              Icons.local_grocery_store_outlined,
                              color: Colors.green,
                              size: 18,
                            ),
                            SizedBox(width: 5),
                            Text(
                              "UdaanBiz",
                              style: TextStyle(fontSize: 12),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const Padding(
                              padding: EdgeInsets.only(top: 10.0, left: 0.0),
                              child: Text(
                                "Bill Date",
                                style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold),
                              ),
                            ),
                            const SizedBox(width: 5),
                            const Icon(
                              Icons.date_range,
                              color: Colors.green,
                              size: 18,
                            ),
                            const SizedBox(width: 5),
                            Text(DateFormat('dd-MM-yyyy').format(DateTime.now(),),style: const TextStyle(fontSize: 12),),
                          ],
                        ),
                        const SizedBox(height: 10),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 2,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 8.0, top: 5.0),
                              child: Text('Product Item 1'),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 160.0, top: 5.0),
                              child: Text('Rate (₹)'),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Padding(
                          padding: const EdgeInsets.symmetric(horizontal: 10),
                          child: Row(
                            children: List.generate(
                              35,
                                  (index) => Container(
                                margin: const EdgeInsets.symmetric(horizontal: 2),
                                height: 2,
                                width: 5,
                                color: Colors.green,
                              ),
                            ),
                          ),
                        ),
                        Expanded(
                          child:Consumer<TransitionHistoryProvider>(builder: (context, value, child) {
                            value.transitionList.toSet().toList();
                            return ListView.builder(
                              itemCount: 5,
                              itemBuilder: (context, index) => Row(
                                children: [
                                  Padding(
                                    padding: const EdgeInsets.only(left: 5, top: 10),
                                    child: Text("Product Item ${index + 1}"),
                                  ),
                                  const Padding(
                                    padding: EdgeInsets.only(left: 160, top: 10),
                                    child: Text("1500/"),
                                  ),
                                ],
                              ),
                            );
                          },),
                        ),
                        const Padding(
                          padding: EdgeInsets.symmetric(horizontal: 10),
                          child: Divider(
                            color: Colors.green,
                            thickness: 1,
                            indent: 0,
                            endIndent: 0,
                          ),
                        ),
                        const Row(
                          children: [
                            Padding(
                              padding: EdgeInsets.only(left: 10, top: 5),
                              child: Text("Total Amount"),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 150, top: 5),
                              child: Text("75000/"),
                            ),
                          ],
                        ),
                        Row(
                          children: [
                            Padding(
                              padding: const EdgeInsets.only(left: 10, top: 5),
                              child: InstaImageViewer(
                                child: SizedBox(
                                  height: 40,
                                  width: 40,
                                  child: Image.asset(
                                    "assets/images/shakil_upi_scaner.jpg",
                                  ),
                                ),
                              ),
                            ),
                            Padding(
                              padding: const EdgeInsets.only(left: 170, top: 5),
                              child: IconButton(onPressed: () {

                              }, icon: const Icon(Icons.send,color: Colors.green,size: 30,)),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              )
            ],
          );
        },),
      );
  }

  void datePiker() async{
    DateTime? datePicker = await showDatePicker(context: context,
        firstDate: DateTime(2020),
        initialDate: DateTime.now(),
        lastDate: DateTime.now());
    if(datePicker != null){
      if (kDebugMode) {
        print("date selected ${datePicker.day}");
      }
    }
  }
}